# -*- coding: utf-8 -*-
"""LinearRegression_salary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6vI4O0DKAO5iK7r7RwMf85klb6cO7eL
"""

import numpy as np
import pandas as pd
df=pd.read_excel('/content/salary slr.xlsx')
df
df.shape
df.info()
df.isnull().sum()

x=df['YearsExperience']
y=df['Salary']
import statsmodels.api as sm
x=sm.add_constant(x)
model=sm.OLS(y,x)
result=model.fit()
result.summary()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

lr=LinearRegression()
lr.fit(x_train,y_train)

from sklearn.metrics import r2_score,mean_squared_error
y_pred=lr.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
r2