# -*- coding: utf-8 -*-
"""Python_Final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2kimHIwIt_KnlC6IrhxQH8OG4c1THIy
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df=pd.read_csv('/content/sales_data.csv')

df

df.isnull().sum()

df.isnull()

df.dropna(inplace=True)
df.isnull().sum()

df.describe()

df.info()

df.count()

df.columns

df.head()

df

df.groupby('Sales').sum()

df.groupby('Sales').sum()

print('The average sales is :')
print(df['Sales'].mean())

df[['Category','Quantity']].sum()

print(df['Quantity'].sum())

df.sort_values(by='Sales',ascending=False)

df.groupby('Product')['Quantity'].sum().sort_values(ascending=False).head(1)

sns.boxplot(x='Category', y='Sales', data=df)
plt.show()

plt.hist(df['Sales'])
plt.show()

plt.boxplot(df['Sales'])
plt.show()

sns.barplot(x='Quantity',y='Product',data=df)
plt.show()

sns.countplot(x='Region',data=df)
plt.ylabel('Orders')
plt.show()

sns.boxplot(x='Region',y='Sales',data=df)
plt.show()

sns.violinplot(x='Region',y='Sales',data=df)
plt.show()